<?php

/**
 * @file
 * Main functions and methods for the "Simple hierarchical select" module.
 */

/**
 * List all javascript classes used to create models and views in the widget.
 *
 * @param string $field_name
 *   Name of field to get the definitions for.
 *
 * @see hook_shs_class_definitions_alter()
 *
 * @return array
 *   List of javascript classes keyed by type ("models", "views").
 */
function shs_get_class_definitions($field_name) {
  $definitions = [
    'models' => [
      'app' => 'Drupal.shs.AppModel',
      'container' => 'Drupal.shs.ContainerModel',
      'widget' => 'Drupal.shs.WidgetModel',
      'widgetItem' => 'Drupal.shs.WidgetItemModel',
      'widgetItemOption' => 'Drupal.shs.WidgetItemOptionModel',
    ],
    'views' => [
      'app' => 'Drupal.shs.AppView',
      'addNew' => 'Drupal.shs.AddNewView',
      'container' => 'Drupal.shs.ContainerView',
      'widget' => 'Drupal.shs.WidgetView',
      'widgetItem' => 'Drupal.shs.WidgetItemView',
    ],
  ];

  $hooks = [
    'shs_class_definitions',
    "shs_{$field_name}_class_definitions",
  ];

  // Allow other modules to override the list of class definitions.
  \Drupal::moduleHandler()->alter($hooks, $definitions);

  return $definitions;
}

  /**
   * Load parents for default values.
   *
   * @param array $default_values
   *   List of default values of the widget.
   * @param array $settings
   *   Widget settings.
   *
   * @return array
   *   List of parents for each default value.
   */
  function shs_term_get_parents($default_values, $settings, $target_type) {
    $parents = [];
    if (!is_array($default_values)) {
      $default_values = [$default_values];
    }
    foreach ($default_values as $delta => $value) {
      if ($settings['anyValue'] === $value) {
        $parents[$delta] = [
          [
            'parent' => 0,
            'defaultValue' => $settings['anyValue'],
          ]
        ];
        continue;
      }
      try {
        $storage = \Drupal::entityTypeManager()->getStorage($target_type);
        $parent_terms = array_reverse(array_keys($storage->loadAllParents($value)));
        $keys = array_merge([0], $parent_terms);
        $values = array_merge($parent_terms, [$value]);
        $parents[$delta] = [];
        foreach ($keys as $index => $key) {
          $parents[$delta][] = [
            'parent' => $key,
            'defaultValue' => $values[$index] ? : $settings['anyValue'],
          ];
        }
      }
      catch (Exception $ex) {
        $parents[$delta] = [
          [
            'parent' => 0,
            'defaultValue' => $settings['anyValue'],
          ]
        ];
      }
    }
    return $parents;
  }
